[build]
  base = "."
  command = "npm run build"
  publish = "frontend/build"
  functions = "backend"

[functions]
  directory = "backend"
  node_bundler = "esbuild"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = ["node_modules", "frontend/node_modules"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200